import { KlipperConfigHelper } from '@/server/helpers/klipper-config';
import { PrinterConfiguration } from '@/zods/printer-configuration';

export const template = async (config: PrinterConfiguration, helper: KlipperConfigHelper) => `
# WARNING. THIS FILE IS GENERATED BY THE RATICAL CONFIGURATOR.
# CHANGES YOU MAKE HERE WILL BE OVERWRITTEN. KEEP YOUR CHANGES IN PRINTER.CFG.
# Config generated for ${config.printer.manufacturer} ${config.printer.name} ${config.size.x}
# Documentation: https://github.com/coolio986/ratical

#############################################################################################################
### CONTROLBOARD & TOOLBOARD
#############################################################################################################
${helper.renderBoards()}

#############################################################################################################
### BASE SETUP
#############################################################################################################
${helper.renderBase()}
[include Ratical/printers/voron-v24/voron-v24.cfg]
[include Ratical/printers/voron-v24/macros.cfg]
[include Ratical/printers/voron-v24/${config.size.x}.cfg]

# Extruder
${helper.renderExtruder()}

# Hotend
${helper.renderHotend()}

# ADXL345 resonance testing configuration
${helper.renderInputShaper(config.size)}

#############################################################################################################
### STEPPER MOTORS, DRIVERS & SPEED LIMITS
#############################################################################################################
${helper.renderMotorSections()}
${helper.renderServoEnableDelay()}
${helper.renderSpeedLimits()}

[bed_mesh]
speed: ${helper.getMacroTravelSpeed()}

[quad_gantry_level]
speed: ${helper.getMacroTravelSpeed()}

#############################################################################################################
### HOMING
#############################################################################################################
${helper.renderProbeIncludes()}
${helper.renderEndstopSection()}

#############################################################################################################
### FANS
#############################################################################################################
${helper.renderFans()}

#############################################################################################################
### ACCESSORIES
#############################################################################################################
${await helper.renderFilamentSensorsAsync()}

${await helper.renderChamberLightingAsync()}

${await helper.renderChamberAirFilterAsync()}

#############################################################################################################
### MACRO CONFIGURATION
#############################################################################################################
${helper.renderMacros()}

# Macro variable overrides
[gcode_macro Ratical]
${helper.renderMacroVariableOverrides()}

# Save variables
${helper.renderSaveVariables()}
`;

export const initialPrinterCfg = (config: PrinterConfiguration, helper: KlipperConfigHelper) => `
#############################################################################################################
### CONFIGURATION GENERATED BY THE RATICAL CONFIGURATOR
### Everything below [include Ratical.cfg] will override default Ratical behavior
#############################################################################################################
[include Ratical.cfg]

#############################################################################################################
### MACRO CONFIGURATION
### Configure the behavior of Ratical macros
### See: https://github.com/coolio986/ratical/docs/configuration/macros
#############################################################################################################
[gcode_macro Ratical]
variable_relative_extrusion: False
variable_preheat_extruder: True
variable_calibrate_bed_mesh: True
variable_nozzle_priming: "primeblob"
variable_start_print_park_in: "front"
variable_start_print_park_z_height: 50
variable_end_print_park_in: "back"
variable_pause_print_park_in: "front"

#############################################################################################################
### USER OVERRIDES & CUSTOM CONFIGURATION
### Anything custom you want to add, or Ratical configuration you want to override, do it here.
### This section is pre-populated with the most common settings you may want to change.
### See: https://github.com/coolio986/ratical/docs/configuration/includes-and-overrides
###
### It is recommended that you follow these steps to properly calibrate your printer:
### 0) Sanity check and PID Tuning: https://www.klipper3d.org/Config_checks.html
### 1) ${helper.renderZOffsetGuidance('###    ')}
### 2) Pressure Advance: https://www.klipper3d.org/Pressure_Advance.html
### 3) Skew Correction: https://www.klipper3d.org/Skew_Correction.html
### 4) Resonance Compensation: https://www.klipper3d.org/Resonance_Compensation.html
### Ratical has dedicated macro's to generate shaper graphs for deeper analysis (requires accelerometer).
### Use MEASURE_COREXY_BELT_TENSION to compare tension between belts, and use
### GENERATE_SHAPER_GRAPHS to generate the resonance graphs for analysing and manually entering input shaper
### configuration.
### You can run SHAPER_CALIBRATE to automatically calibrate your input shaper configuration, if you just want
### to get started.
### Additionally, you can use the Realtime Analysis Tool to analyze your printer's performance in real-time.
### Read more about klipper here: https://www.klipper3d.org/Overview.html
#############################################################################################################


${helper.renderUserStepperSections({
	x: {
		directionInverted: true,
		rotationComment: '40 for 20 tooth 2GT pulleys, 32 for 16 tooth 2GT pulleys',
		limits: (margin) => ({
			min: 0 - margin.min,
			max: config.size.x + margin.max,
			endstop: config.size.x + margin.max,
		}),
	},
	y: {
		directionInverted: false,
		rotationComment: '40 for 20 tooth 2GT pulleys, 32 for 16 tooth 2GT pulleys',
		limits: (margin) => ({
			min: 0 - margin.min,
			max: config.size.y + margin.max,
			endstop: config.size.y + margin.max,
		}),
	},
	z: {
		directionInverted: true,
		limits: {
			min: 0,
			max: config.size.z,
		},
	},
	z1: {
		directionInverted: true,
	},
	z2: {
		directionInverted: true,
	},
	z3: {
		directionInverted: true,
	},
	extruder: {
		directionInverted: true,
		additionalLines: [
			'#pressure_advance: 0.05 # Check https://www.klipper3d.org/Pressure_Advance.html for pressure advance tuning.',
			'control: pid',
			'pid_kp: 21.673',
			'pid_ki: 1.338',
			'pid_kd: 87.776',
		],
	},
})}

[heater_bed]
control: pid
pid_kp: 68.203
pid_ki: 2.842
pid_kd: 409.216

${helper.renderProbePinSection()}

${helper.renderReminders()}
`;
